# Generated by Django 2.1.5 on 2020-05-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_album', models.CharField(max_length=70)),
                ('year_release', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_band', models.CharField(max_length=100)),
                ('year_create', models.CharField(max_length=15)),
                ('members', models.TextField()),
                ('former_members', models.TextField()),
            ],
            options={
                'verbose_name': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GenreMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Band')),
            ],
            options={
                'verbose_name': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='band',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.GenreMusic'),
        ),
        migrations.AddField(
            model_name='album',
            name='band_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Band'),
        ),
    ]
