# Generated by Django 2.1.5 on 2020-05-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='band_id',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='band_id',
            new_name='band',
        ),
    ]
